sudo: required
dist: trusty
language: node_js
node_js:
  - 'stable'
branches:
  except:
  - gh-pages
addons:
  # You can't install latest and beta as addons
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

before_script:
  - npm install web-component-tester
  - npm install bower
  - export PATH=$PWD/node_modules/.bin:$PATH
  - bower install

script:
  - xvfb-run wct --skip-plugin sauce
  - if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct --plugin sauce --skip-plugin local; fi

env:
  global:
  - secure: ApXBDwZyJxcX4W7fpFjKJH6YgHUBomi5vxfSyWqotLmYTxt1wmhKeug1iNx/8DAMSyVOc2ytrclD9lRTgciYqZ8hg9AzLfXEZ4qhKmzuRXv/IpsL+F3Wq+tsr2GtAZjVteATZd6AdTbkvxw/X7cV74+6g1MYnT+hSx1K6Tpg6QQ4uvixGAXszVs1mCxyjFA6rPshe0MMrZZ1OXw9T/aoWpbUJu7BhfN1N+TyoxSb6rTEfO1ogQDQpxXPMfpM/r1RpC3eqnn0eyefJXCUt7Y4O8VsRaI1qpvNSIeP4wXinYHXDGz5fwdRt+fKxB3REMjP3Opz3PIjwjExW95/VTs2gzJ5RLW2X4WC2Ns84WCB0SSYogNRTWTiandH/NINhB7H0ReWHK6EZmBwQ/XERx/8U0cn/gJnbv2IEp6XA1U+47MyMqyonhJfi8Sag7igjY+COvyEfLiZKx3NCn/2OVlZBIrPhs6EVbBNcSMmV6b7/t1/L84X6P0da2Y+NyuTbKXuPqy2CJ0AD2XRREWQCnvMDTEEQXUNeYrDVcc6/Q+vOmZ5mCuVj0MjqQFBcf+INVqzs+dRtg5S36zQCkHiim9kYemSvnBpj5N1R7MGLwDbSoEoSd0GS9EvQdEAHNMEZJuTP1TxvZgGRx6pEetWYxWJNSHfTgQvYRWm7SfMtxpzVtk=
  - secure: O4ScpvHGeSiGt8WOmVbiOTqHDCILFtvS788Ae3u/ueu0l1/B2PbokHeaalv25LhuFVN7p9QJt2jtuvofWux7c+IbaAfTZyEd5IK2rpqum72qaL2qIJwf0aZKnZR7gB2wYDuvyAcJsAVYPV5ciKywU142oHEU6sOTAkKIGNSX2E2Erz9ZAPyKsWZlSaXEdzSb+QidgS0QQYLGz83brjVlbCkH3q+/uDQfrUjjvIg9GX3oPJFc8DsZn02WprnH/kCLT4OpiBVylwyA/PJFt0d3dprC49MlRQvgMEH585hyH5UHJ7ts7u43GHasoSjVSVt0PUoOE60KwyUCbJqzqEHSxXl+ihLCJKLscMicV2VAwPIQwlpxBR/ZKYfAMuDFX92eN+it2oYX9eJaJGOn/3sU3u8ncznpYI7M1Kq2HfNYBAtA3xu66MCcylJrj9IJSTb1+06fvLykGvfbrSLpM5y3dAD/VJoojxIvoR1l1YFu4rFIGI9+l8ZLEzypFjfmg0CJ3ZtcA/bbV2HyFA16gJuAPF63hiBf/QTiORet4Au1WuCCbYrmw4zrDmzfxj54wMG5IErH4YGRqiqak5NHFs+ncumB2L+MxdQ07e760FRFkRq3IVr2XKTNiuw06AkckqC6c/LcsCAb1MNmCoE+qhraOvXBAwfJsnEq/jIjo9VuQtM=
