sudo: false
dist: trusty
language: node_js
node_js: stable
branches:
  except:
  - gh-pages
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
  sauce_connect: true
before_script:
- yarn global add polymer-cli
- polymer install --variants
script:
- xvfb-run polymer test --skip-plugin sauce
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct --plugin sauce --skip-plugin
  local; fi
after_success:
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then openssl aes-256-cbc -k "$DEPLOYSECRET"
  -in deploy.enc -out deploy_key -d; fi
- cd $TRAVIS_BUILD_DIR/scripts
- chmod 755 ghp.sh
- "./ghp.sh"
env:
  global:
  - secure: ErUe6xazO0EkOKfXY1ix8tKkj4cfnCkxxXjpdoTyT4VBjod6iWKzpaQvOQdNhdf0oUewl84Q5kUR0KORHh6yZEKkVhXLOqKouKe3Pu1dKZOZ5dBt5GsBVN+OZKTx/iT43+CasSufI/XLSkjxcCydbLXunt4vRejc0uLVw/xknU9lgrNjSx+uFm+2GUYYsWQOHboJSEi17hR0TMaufnBJwIrBeNwJzgpE/pr+37F8TXnZ/MZ55h/GjuE2xKIiYld1/zUfJnY9azW/qXbHKXme74rjoQkRxnXuQFxC1DBCkIy3i/eGRDPzua5RDvw0wDjPcMrjkB3oU1OpBvJOMRV+4Q/AlyEF6MTpPorOlQoAZg1TplX0K3Xc4TmG+Fznpo02huXD0qyO5dJ7zudc5xCyYLA6aHwEERfRws6BXzz9UMOvzQc+Wb+YGC9LSgoi3uAUgxp+W1Jrmvpd7/bSBilLWhB3j6J9CVGW3DNtcn23Yhx4b2Cbu6oPmCAY8lVT80M0DabTFw6yIl0VjOF5YRuVUxKYBNpnW34JTSHOiDkk3eIO6LDTn5tHxz/4+urODK5HlDqNhscGrcBhzZMYquExkF+0FunEM+rZnRUaU+5/ONjXUnoKzGHjWGjyX9iy0ZeKCkOAzGx7IdD4vyi5ZOsiuVBB7Kwnf/tDpA9sRdznAVI=
  - secure: mGL7S7z0XLk2K+Id/jNnjo4FpGFXTYW8DboPIng72ytTM8BjRFX8DYvtTL/9D6tUk7TKB+6eKA2UomgP3ULzKIxNmLywe8+4neb+R6m9HXfkS70u3GJTA7WmMfrzcVxg+QUBZuDeMsTR92P7frSSQDNcer/2BwwGVg1YrFc5UUq6Y2b78Sb576j7nQ3HNRN5oi507vaowjejitNOuAoBl1lKm+tfZMgCslyXuX9d4d2ZZh8Rp2ueggohqfB7A+zn/mmMhgBrFVsTs4wcrv8HhfQYaYOry3k4vaX98wKGeT0Di7QASX/Zu3FiFvdZN0ptJjHoQPUBbthsmQUyVvOwQyztC92m2V5fND6s48YT60mntBL8w7kwpy+oZ3Sop8NJDTHclgYmUnGelq5ys6noP+nCyEj8a0uuAzG4Tbr5g61rCkAobmmd3GpZIFcVoOUQgLI8u2aVPM+7QT+pNQkkE3y8zfwCEcln2nMKNqpgvvTARH0fs16aOSIqCtNxeX0RjDSMIwlfSuLP7vKdVockPvR2yl/mHOdOLZTQe0TL73u6DHy2uP/dPCphraLyCc55rJNCS/mrtAOK6BUqQK/ejAfjkOAE0v/T+F2l16DYKSQXEMlPz7M+AwWYTFTHd9irHgSCXX6XYhNRToHvamvYSymx38tYXjhFC6UfdIh/1qg=
  - secure: P8U46hwS3WKBz1krhuipXwta6oXq5vIAznUSnlnb/igMQe+ZRlx4LZZrP7j+TCwzqEUek6Db83yeoGBulq/wvefCeGF1+XcAqs3FtNQOFT856hSnt7nlbLEjKCzAzxb/z93UDKVWZAAs+bK+BMIInJk+OSHhiqFL1StXP6zM/kJjvxF4I0UzvPqI6TWG4HCAQppBYL/LHlTgEil7sy1VvSnVlO79CaA2AuY6xMCp2w/t94svfPlRJoGnN+NcjXWq4KI+WuPPSa7GBshg/MU/IxtlGaXrLbhgwE3dHFYsMjv/QSXBcdc7encgnNrTOe18oQhBGxVP385qSYRuB/VqOPz9t0h8dcnzpxJauDf0meHjTcW3uB01Lhc5ZHvvzN1u2lnlzQb8BZPdvBos0kiQoen3RB6q0I1AU8jiBu72esVtKTP/QfYhr4n+i52g8DoJReeLVh5vB1HbHqHS5vNWPCSqjnkTwECM1te1oS6+/GCl3jnbxOuk3QpdMoiY/wm4uvfXJwXVSZF2qRCNFMXB1oXGhTvWZxr3FTyp2Sa35ydMTy/znCzSWjKwCDwP1b2NVDBB+8R9xCoj0tkL716ku0VnQbfFEADjhJG+XeCRrrFv4MMhT5XG9mYBjk3X/Qa9Xm/+yBL4kLK8MC5c0z8EV5SujSYjj5te0cQHGpQ+cxU=
  - secure: eH+9y2bWH5X6AuvR+SQVvRCAH9VOHNQcxfX6kFdui4ReBvbON3vBSbuYHwX9EnhKcGd9g3Z861OvnZJad06VoYvzqhitVNFiCC5WA92PfBr3cuCSN3CekboicDcUPVrA+v68xiAI85Xvmas4ksJm9U2P/OoFNuiQIl0ss42K3FEsXeRJVSbzfV0tabbSG43s5UVKThNv5xnmbDZrtO1F26CCavBwYJuSgDkkgRwg+JqLpTffUq6lk+9YdValL+qv3GbOB9goAeDuYWMvcKFO5LtbH+LJ3M0TiWLeSQsT8KXCNR1fylMi0a83Nam+mhIF6gHCgopUHjQytxApKUapMcItzFbizneK4veNQShiGgNUHRkm6BaFNxeeoSVFL2mrU4Uot47uP83fUzuwp7RDMKOJwQ7g8PuWS4KEAI8a5he2s4seefg1s0L+mwHtcJMAE/FxDxpZwWUV7YZT5T7cIlgU67UmPrpJPiJrw5klTCYXZzgMY+cO4F3mUD++j2QUyk0Jb201XkCjUEb02RHXlmF3F1AuVkPT9Cy8eK2/Of6FdVUDk+D721AVYxfSU5Khas0CM6fMLHYP0DAbbtQPf4myiEG6IUTMdl43rFsHRf5N0AR6h1t2bMACY3pL1joKhG2pBWEzIQjn4d4O7V30aGeJ/PruC406zE5aT1/GrF8=
